// Coverage + determinism tests for the per-scope archive generator.
// Ensures the Archive and Background sheets are NEVER empty for any
// (sub-category × supplier × series) selection.
import { describe, it, expect } from "vitest";
import {
  generateHistoricalPromosForScope,
  generateKpisForScope,
} from "./mock-archive-generator";
import { getSuppliersForSubCategory } from "./mock-subcategory-suppliers";
import { getSeriesForSupplierAndSubCategory } from "./mock-supplier-series";
import { PROMO_GROUPS } from "./mock-promo-taxonomy";

function allSubCategoryIds(): string[] {
  const ids: string[] = [];
  for (const group of PROMO_GROUPS) {
    for (const department of group.departments) {
      for (const category of department.categories) {
        for (const sub of category.subCategories) {
          ids.push(sub.id);
        }
      }
    }
  }
  return ids;
}

describe("per-scope archive generator — full coverage", () => {
  it("yields >= 8 historical promos for every sub-category alone", () => {
    const failures: string[] = [];
    for (const subId of allSubCategoryIds()) {
      const promos = generateHistoricalPromosForScope({
        subcategoryId: subId,
        supplierId: "",
        series: "",
      });
      if (promos.length < 8) failures.push(`${subId} → ${promos.length}`);
    }
    expect(failures).toEqual([]);
  });

  it("yields >= 5 KPIs for every sub-category", () => {
    const failures: string[] = [];
    for (const subId of allSubCategoryIds()) {
      const kpis = generateKpisForScope({
        subcategoryId: subId,
        supplierId: "",
        series: "",
      });
      if (kpis.length < 5) failures.push(`${subId} → ${kpis.length} KPIs`);
    }
    expect(failures).toEqual([]);
  });

  it("yields populated content for every supplier × subcategory pair declared in the supplier mapping", () => {
    const failures: string[] = [];
    for (const subId of allSubCategoryIds()) {
      const supplierIds = getSuppliersForSubCategory(subId);
      for (const supplierId of supplierIds) {
        const promos = generateHistoricalPromosForScope({
          subcategoryId: subId,
          supplierId,
          series: "",
        });
        const kpis = generateKpisForScope({
          subcategoryId: subId,
          supplierId,
          series: "",
        });
        if (promos.length === 0 || kpis.length === 0) {
          failures.push(`${supplierId} × ${subId}`);
        }
      }
    }
    expect(failures).toEqual([]);
  });

  it("yields populated content for the full triple (subcategory × supplier × series) — the user's tuna gap", () => {
    // שסטוביץ × טונה × <auto-generated series>
    const series = getSeriesForSupplierAndSubCategory("sup-08", "tuna");
    expect(series.length).toBeGreaterThan(0);
    const seriesPick = series[0]!;
    const promos = generateHistoricalPromosForScope({
      subcategoryId: "tuna",
      supplierId: "sup-08",
      series: seriesPick,
    });
    expect(promos.length).toBeGreaterThanOrEqual(3);
    expect(promos[0]?.name).toContain("שסטוביץ");
  });

  it("does not emit a Stockout Rate KPI", () => {
    const kpis = generateKpisForScope({
      subcategoryId: "tea",
      supplierId: "",
      series: "",
    });
    const ids = kpis.map((k) => k.id);
    const labels = kpis.map((k) => k.label);
    expect(ids.some((id) => id.startsWith("stockout"))).toBe(false);
    expect(labels).not.toContain("Stockout Rate");
    expect(labels).not.toContain("שיעור חוסרים");
  });

  it("labels the gross-margin KPI in canonical Hebrew (רווחיות גולמית) and floors it at 28%", () => {
    const failures: string[] = [];
    for (const subId of allSubCategoryIds()) {
      const kpis = generateKpisForScope({
        subcategoryId: subId,
        supplierId: "",
        series: "",
      });
      const margin = kpis.find((k) => k.id.startsWith("gross-margin"));
      if (!margin) {
        failures.push(`${subId} → no gross-margin KPI`);
        continue;
      }
      if (margin.label !== "רווחיות גולמית") {
        failures.push(`${subId} → label="${margin.label}"`);
      }
      if (margin.rawValue < 28) {
        failures.push(`${subId} → rawValue=${margin.rawValue} (<28)`);
      }
      if (margin.status !== "good") {
        failures.push(`${subId} → status=${margin.status} (not good)`);
      }
    }
    expect(failures).toEqual([]);
  });

  it("scales count by scope precision: sub-cat=8, supplier=7, series=6", () => {
    const subOnly = generateHistoricalPromosForScope({
      subcategoryId: "tea",
      supplierId: "",
      series: "",
    });
    const withSupplier = generateHistoricalPromosForScope({
      subcategoryId: "tea",
      supplierId: "sup-22",
      series: "",
    });
    const withSeries = generateHistoricalPromosForScope({
      subcategoryId: "tea",
      supplierId: "sup-22",
      series: "תה ירוק",
    });
    expect(subOnly.length).toBe(8);
    expect(withSupplier.length).toBe(7);
    expect(withSeries.length).toBe(6);
  });

  it("is deterministic — same scope always produces the same output", () => {
    const a = generateHistoricalPromosForScope({
      subcategoryId: "tea",
      supplierId: "sup-22",
      series: "תה ירוק",
    });
    const b = generateHistoricalPromosForScope({
      subcategoryId: "tea",
      supplierId: "sup-22",
      series: "תה ירוק",
    });
    expect(a).toEqual(b);
  });

  it("changes output when scope changes", () => {
    const tunaPromos = generateHistoricalPromosForScope({
      subcategoryId: "tuna",
      supplierId: "sup-08",
      series: "",
    });
    const teaPromos = generateHistoricalPromosForScope({
      subcategoryId: "tea",
      supplierId: "sup-22",
      series: "",
    });
    expect(tunaPromos[0]?.name).not.toEqual(teaPromos[0]?.name);
  });
});
